router_name           = "test-router"
region                = "northamerica-northeast2"
network-id            = "test_network_id"
router_nat_name       = "test-nat"
nat_ip_ranges         = "ALL_SUBNETWORKS_ALL_IP_RANGES"
nat_allocation_option = "AUTO_ONLY"