namespace:
	kubectl apply -f k8s-but-use-make/namespace.yaml
argocd:
	kubectl apply -n argocd -f k8s-but-use-make/argocd.yaml
certificate:
	kubectl apply -n argocd -f k8s-but-use-make/managedcertificate.yaml