name: Argo-setup 

on:
  push:
    paths: 
      - 'argocd/**'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: argocd
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - id: 'authGCP'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/797097160987/locations/global/workloadIdentityPools/github-id-pool/providers/github-provider-id'
        service_account: 'gh-service-account@agile-tangent-401105.iam.gserviceaccount.com'
    
    - id: 'gke-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'primary-cluster'
        location: 'northamerica-northeast2-a'

        # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'argo-cd'
      name: 'Installing Argocd'
      run: 'make argocd'
    - id: 'argocd-ingress'
      name: 'Creating ingress'
      run: 'make ingress'