name: 'terraform-apply'

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'workspace unique identifier(only when modifying)'

permissions:
  contents: read

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: WorkingDirectory
      run: pwd

    # # Step to generate unique id for this run
    # - id: UUIDGen
    #   name: Generating UUID
    #   if: github.event.inputs.input1 == ''  
    #   run: |
    #     echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

    # gcp authorization with workload identity federation
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/797097160987/locations/global/workloadIdentityPools/github-id-pool/providers/github-provider'
        service_account: 'gh-service-account@agile-tangent-401105.iam.gserviceaccount.com'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # setup workspace with given workspace guid
    - name: Setup Workspace - Existing state file
      if: github.event.inputs.workspace != ''
      run: |
        terraform workspace select ${{ github.event.inputs.workspace }}

    # create unique id to create new workspace
    # create new workspace to create new state file
    - name: Setup Workspace - New state file
      if: github.event.inputs.workspace == ''
      run: |
        uuid=$(uuidgen)
        echo $uuid
        terraform workspace new $uuid

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -out=tfplan
    - name: Terraform Apply
      id: terraformapply
      run: terraform apply -auto-approve tfplan
    - name: Terraform Destroy on failure
      if: steps.terraformapply.outcome == 'failure'
      run: terraform destroy -auto-approve
