name: buildNpush

on:
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - id: 'authGCP'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: access_token
        # create_credentials_file: true
        workload_identity_provider: 'projects/797097160987/locations/global/workloadIdentityPools/swath-gh-idenity-pool/providers/swath-pool-provider-id'
        service_account: 'swath-service-account@agile-tangent-401105.iam.gserviceaccount.com'
        # access_token_lifetime: 300s